default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sellshare_development

test:
  <<: *default
  database: sellshare_test

production:
  <<: *default
  database: sellshare_production
  username: sellshare
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  # adapter: postgresql
  # encoding: utf8
  # pool: 5
  # database: sellshare_production
  # # username: root
  # socket: /var/lib/psql/psql.sock
  # port:     5432