default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sellshare_development

test:
  <<: *default
  database: sellshare_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  # database: sellshare_production
  # username: sellshare
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>
